namespace SuperMarket
{
    partial class Categories
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Categories));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.Refresh_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label6 = new System.Windows.Forms.Label();
            this.Delete_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Edit_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Seller_btn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.close = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.Description_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.catName_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.catID_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Product_btn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.panel1 = new System.Windows.Forms.Panel();
            this.Categories_grid = new Guna.UI2.WinForms.Guna2DataGridView();
            this.logout = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Categories_grid)).BeginInit();
            this.SuspendLayout();
            // 
            // Refresh_btn
            // 
            this.Refresh_btn.AllowAnimations = true;
            this.Refresh_btn.AllowMouseEffects = true;
            this.Refresh_btn.AllowToggling = false;
            this.Refresh_btn.AnimationSpeed = 200;
            this.Refresh_btn.AutoGenerateColors = false;
            this.Refresh_btn.AutoRoundBorders = false;
            this.Refresh_btn.AutoSizeLeftIcon = true;
            this.Refresh_btn.AutoSizeRightIcon = true;
            this.Refresh_btn.BackColor = System.Drawing.Color.Transparent;
            this.Refresh_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Refresh_btn.BackgroundImage")));
            this.Refresh_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.ButtonText = "Refresh";
            this.Refresh_btn.ButtonTextMarginLeft = 0;
            this.Refresh_btn.ColorContrastOnClick = 45;
            this.Refresh_btn.ColorContrastOnHover = 45;
            this.Refresh_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Refresh_btn.CustomizableEdges = borderEdges1;
            this.Refresh_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Refresh_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Refresh_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Refresh_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Refresh_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Refresh_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Refresh_btn.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Refresh_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Refresh_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Refresh_btn.IconMarginLeft = 11;
            this.Refresh_btn.IconPadding = 10;
            this.Refresh_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Refresh_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Refresh_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Refresh_btn.IconSize = 25;
            this.Refresh_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Refresh_btn.IdleBorderRadius = 3;
            this.Refresh_btn.IdleBorderThickness = 2;
            this.Refresh_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.IdleIconLeftImage = null;
            this.Refresh_btn.IdleIconRightImage = null;
            this.Refresh_btn.IndicateFocus = false;
            this.Refresh_btn.Location = new System.Drawing.Point(891, 70);
            this.Refresh_btn.Name = "Refresh_btn";
            this.Refresh_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Refresh_btn.OnDisabledState.BorderRadius = 3;
            this.Refresh_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnDisabledState.BorderThickness = 2;
            this.Refresh_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Refresh_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Refresh_btn.OnDisabledState.IconLeftImage = null;
            this.Refresh_btn.OnDisabledState.IconRightImage = null;
            this.Refresh_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Refresh_btn.onHoverState.BorderRadius = 3;
            this.Refresh_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.onHoverState.BorderThickness = 2;
            this.Refresh_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Refresh_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Refresh_btn.onHoverState.IconLeftImage = null;
            this.Refresh_btn.onHoverState.IconRightImage = null;
            this.Refresh_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Refresh_btn.OnIdleState.BorderRadius = 3;
            this.Refresh_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnIdleState.BorderThickness = 2;
            this.Refresh_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.OnIdleState.IconLeftImage = null;
            this.Refresh_btn.OnIdleState.IconRightImage = null;
            this.Refresh_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Refresh_btn.OnPressedState.BorderRadius = 3;
            this.Refresh_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnPressedState.BorderThickness = 2;
            this.Refresh_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Refresh_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.OnPressedState.IconLeftImage = null;
            this.Refresh_btn.OnPressedState.IconRightImage = null;
            this.Refresh_btn.Size = new System.Drawing.Size(102, 46);
            this.Refresh_btn.TabIndex = 20;
            this.Refresh_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Refresh_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Refresh_btn.TextMarginLeft = 0;
            this.Refresh_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Refresh_btn.UseDefaultRadiusAndThickness = true;
            this.Refresh_btn.Click += new System.EventHandler(this.Refresh_btn_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.label6.Font = new System.Drawing.Font("Century Gothic", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(334, 11);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(354, 41);
            this.label6.TabIndex = 19;
            this.label6.Text = "Manage Categories";
            this.label6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // Delete_btn
            // 
            this.Delete_btn.AllowAnimations = true;
            this.Delete_btn.AllowMouseEffects = true;
            this.Delete_btn.AllowToggling = false;
            this.Delete_btn.AnimationSpeed = 200;
            this.Delete_btn.AutoGenerateColors = false;
            this.Delete_btn.AutoRoundBorders = false;
            this.Delete_btn.AutoSizeLeftIcon = true;
            this.Delete_btn.AutoSizeRightIcon = true;
            this.Delete_btn.BackColor = System.Drawing.Color.Transparent;
            this.Delete_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delete_btn.BackgroundImage")));
            this.Delete_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.ButtonText = "Delete";
            this.Delete_btn.ButtonTextMarginLeft = 0;
            this.Delete_btn.ColorContrastOnClick = 45;
            this.Delete_btn.ColorContrastOnHover = 45;
            this.Delete_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Delete_btn.CustomizableEdges = borderEdges2;
            this.Delete_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Delete_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Delete_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Delete_btn.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Delete_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Delete_btn.IconMarginLeft = 11;
            this.Delete_btn.IconPadding = 10;
            this.Delete_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Delete_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Delete_btn.IconSize = 25;
            this.Delete_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Delete_btn.IdleBorderRadius = 3;
            this.Delete_btn.IdleBorderThickness = 2;
            this.Delete_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.IdleIconLeftImage = null;
            this.Delete_btn.IdleIconRightImage = null;
            this.Delete_btn.IndicateFocus = false;
            this.Delete_btn.Location = new System.Drawing.Point(257, 301);
            this.Delete_btn.Name = "Delete_btn";
            this.Delete_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn.OnDisabledState.BorderRadius = 3;
            this.Delete_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnDisabledState.BorderThickness = 2;
            this.Delete_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn.OnDisabledState.IconLeftImage = null;
            this.Delete_btn.OnDisabledState.IconRightImage = null;
            this.Delete_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Delete_btn.onHoverState.BorderRadius = 3;
            this.Delete_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.onHoverState.BorderThickness = 2;
            this.Delete_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Delete_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Delete_btn.onHoverState.IconLeftImage = null;
            this.Delete_btn.onHoverState.IconRightImage = null;
            this.Delete_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Delete_btn.OnIdleState.BorderRadius = 3;
            this.Delete_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnIdleState.BorderThickness = 2;
            this.Delete_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.OnIdleState.IconLeftImage = null;
            this.Delete_btn.OnIdleState.IconRightImage = null;
            this.Delete_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn.OnPressedState.BorderRadius = 3;
            this.Delete_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnPressedState.BorderThickness = 2;
            this.Delete_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.OnPressedState.IconLeftImage = null;
            this.Delete_btn.OnPressedState.IconRightImage = null;
            this.Delete_btn.Size = new System.Drawing.Size(102, 46);
            this.Delete_btn.TabIndex = 18;
            this.Delete_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Delete_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Delete_btn.TextMarginLeft = 0;
            this.Delete_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Delete_btn.UseDefaultRadiusAndThickness = true;
            this.Delete_btn.Click += new System.EventHandler(this.Delete_btn_Click);
            // 
            // Edit_btn
            // 
            this.Edit_btn.AllowAnimations = true;
            this.Edit_btn.AllowMouseEffects = true;
            this.Edit_btn.AllowToggling = false;
            this.Edit_btn.AnimationSpeed = 200;
            this.Edit_btn.AutoGenerateColors = false;
            this.Edit_btn.AutoRoundBorders = false;
            this.Edit_btn.AutoSizeLeftIcon = true;
            this.Edit_btn.AutoSizeRightIcon = true;
            this.Edit_btn.BackColor = System.Drawing.Color.Transparent;
            this.Edit_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit_btn.BackgroundImage")));
            this.Edit_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.ButtonText = "Edit";
            this.Edit_btn.ButtonTextMarginLeft = 0;
            this.Edit_btn.ColorContrastOnClick = 45;
            this.Edit_btn.ColorContrastOnHover = 45;
            this.Edit_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Edit_btn.CustomizableEdges = borderEdges3;
            this.Edit_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Edit_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Edit_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Edit_btn.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Edit_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Edit_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Edit_btn.IconMarginLeft = 11;
            this.Edit_btn.IconPadding = 10;
            this.Edit_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Edit_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Edit_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Edit_btn.IconSize = 25;
            this.Edit_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Edit_btn.IdleBorderRadius = 3;
            this.Edit_btn.IdleBorderThickness = 2;
            this.Edit_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.IdleIconLeftImage = null;
            this.Edit_btn.IdleIconRightImage = null;
            this.Edit_btn.IndicateFocus = false;
            this.Edit_btn.Location = new System.Drawing.Point(140, 301);
            this.Edit_btn.Name = "Edit_btn";
            this.Edit_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit_btn.OnDisabledState.BorderRadius = 3;
            this.Edit_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnDisabledState.BorderThickness = 2;
            this.Edit_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit_btn.OnDisabledState.IconLeftImage = null;
            this.Edit_btn.OnDisabledState.IconRightImage = null;
            this.Edit_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Edit_btn.onHoverState.BorderRadius = 3;
            this.Edit_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.onHoverState.BorderThickness = 2;
            this.Edit_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Edit_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Edit_btn.onHoverState.IconLeftImage = null;
            this.Edit_btn.onHoverState.IconRightImage = null;
            this.Edit_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Edit_btn.OnIdleState.BorderRadius = 3;
            this.Edit_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnIdleState.BorderThickness = 2;
            this.Edit_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.OnIdleState.IconLeftImage = null;
            this.Edit_btn.OnIdleState.IconRightImage = null;
            this.Edit_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit_btn.OnPressedState.BorderRadius = 3;
            this.Edit_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnPressedState.BorderThickness = 2;
            this.Edit_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.OnPressedState.IconLeftImage = null;
            this.Edit_btn.OnPressedState.IconRightImage = null;
            this.Edit_btn.Size = new System.Drawing.Size(102, 46);
            this.Edit_btn.TabIndex = 17;
            this.Edit_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Edit_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Edit_btn.TextMarginLeft = 0;
            this.Edit_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Edit_btn.UseDefaultRadiusAndThickness = true;
            this.Edit_btn.Click += new System.EventHandler(this.Edit_btn_Click);
            // 
            // Add_btn
            // 
            this.Add_btn.AllowAnimations = true;
            this.Add_btn.AllowMouseEffects = true;
            this.Add_btn.AllowToggling = false;
            this.Add_btn.AnimationSpeed = 200;
            this.Add_btn.AutoGenerateColors = false;
            this.Add_btn.AutoRoundBorders = false;
            this.Add_btn.AutoSizeLeftIcon = true;
            this.Add_btn.AutoSizeRightIcon = true;
            this.Add_btn.BackColor = System.Drawing.Color.Transparent;
            this.Add_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Add_btn.BackgroundImage")));
            this.Add_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.ButtonText = "Add";
            this.Add_btn.ButtonTextMarginLeft = 0;
            this.Add_btn.ColorContrastOnClick = 45;
            this.Add_btn.ColorContrastOnHover = 45;
            this.Add_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Add_btn.CustomizableEdges = borderEdges4;
            this.Add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Add_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Add_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Add_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Add_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Add_btn.ForeColor = System.Drawing.Color.White;
            this.Add_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Add_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Add_btn.IconMarginLeft = 11;
            this.Add_btn.IconPadding = 10;
            this.Add_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Add_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Add_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Add_btn.IconSize = 25;
            this.Add_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Add_btn.IdleBorderRadius = 3;
            this.Add_btn.IdleBorderThickness = 2;
            this.Add_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.IdleIconLeftImage = null;
            this.Add_btn.IdleIconRightImage = null;
            this.Add_btn.IndicateFocus = false;
            this.Add_btn.Location = new System.Drawing.Point(23, 301);
            this.Add_btn.Name = "Add_btn";
            this.Add_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Add_btn.OnDisabledState.BorderRadius = 3;
            this.Add_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnDisabledState.BorderThickness = 2;
            this.Add_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Add_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Add_btn.OnDisabledState.IconLeftImage = null;
            this.Add_btn.OnDisabledState.IconRightImage = null;
            this.Add_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Add_btn.onHoverState.BorderRadius = 3;
            this.Add_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.onHoverState.BorderThickness = 2;
            this.Add_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Add_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Add_btn.onHoverState.IconLeftImage = null;
            this.Add_btn.onHoverState.IconRightImage = null;
            this.Add_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Add_btn.OnIdleState.BorderRadius = 3;
            this.Add_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnIdleState.BorderThickness = 2;
            this.Add_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Add_btn.OnIdleState.IconLeftImage = null;
            this.Add_btn.OnIdleState.IconRightImage = null;
            this.Add_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Add_btn.OnPressedState.BorderRadius = 3;
            this.Add_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnPressedState.BorderThickness = 2;
            this.Add_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Add_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Add_btn.OnPressedState.IconLeftImage = null;
            this.Add_btn.OnPressedState.IconRightImage = null;
            this.Add_btn.Size = new System.Drawing.Size(102, 46);
            this.Add_btn.TabIndex = 16;
            this.Add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Add_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Add_btn.TextMarginLeft = 0;
            this.Add_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Add_btn.UseDefaultRadiusAndThickness = true;
            this.Add_btn.Click += new System.EventHandler(this.Add_btn_Click);
            // 
            // Seller_btn
            // 
            this.Seller_btn.ActiveBorderThickness = 2;
            this.Seller_btn.ActiveCornerRadius = 20;
            this.Seller_btn.ActiveFillColor = System.Drawing.Color.DodgerBlue;
            this.Seller_btn.ActiveForecolor = System.Drawing.Color.White;
            this.Seller_btn.ActiveLineColor = System.Drawing.Color.DodgerBlue;
            this.Seller_btn.BackColor = System.Drawing.Color.White;
            this.Seller_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Seller_btn.BackgroundImage")));
            this.Seller_btn.ButtonText = "Sellers";
            this.Seller_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Seller_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Seller_btn.ForeColor = System.Drawing.Color.DodgerBlue;
            this.Seller_btn.IdleBorderThickness = 2;
            this.Seller_btn.IdleCornerRadius = 20;
            this.Seller_btn.IdleFillColor = System.Drawing.Color.White;
            this.Seller_btn.IdleForecolor = System.Drawing.Color.DodgerBlue;
            this.Seller_btn.IdleLineColor = System.Drawing.Color.DodgerBlue;
            this.Seller_btn.Location = new System.Drawing.Point(14, 114);
            this.Seller_btn.Margin = new System.Windows.Forms.Padding(5);
            this.Seller_btn.Name = "Seller_btn";
            this.Seller_btn.Size = new System.Drawing.Size(156, 56);
            this.Seller_btn.TabIndex = 21;
            this.Seller_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Seller_btn.Click += new System.EventHandler(this.Seller_btn_Click);
            // 
            // close
            // 
            this.close.AutoSize = true;
            this.close.BackColor = System.Drawing.Color.DodgerBlue;
            this.close.Font = new System.Drawing.Font("Leelawadee", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.close.ForeColor = System.Drawing.Color.White;
            this.close.Location = new System.Drawing.Point(1167, 9);
            this.close.Name = "close";
            this.close.Size = new System.Drawing.Size(21, 23);
            this.close.TabIndex = 20;
            this.close.Text = "x";
            this.close.Click += new System.EventHandler(this.close_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(13, 234);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(133, 23);
            this.label4.TabIndex = 12;
            this.label4.Text = "Description :";
            // 
            // Description_txt
            // 
            this.Description_txt.AcceptsReturn = false;
            this.Description_txt.AcceptsTab = false;
            this.Description_txt.AnimationSpeed = 200;
            this.Description_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Description_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Description_txt.BackColor = System.Drawing.Color.White;
            this.Description_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Description_txt.BackgroundImage")));
            this.Description_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.Description_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Description_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Description_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.Description_txt.BorderRadius = 5;
            this.Description_txt.BorderThickness = 3;
            this.Description_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Description_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Description_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Description_txt.DefaultText = "";
            this.Description_txt.FillColor = System.Drawing.Color.White;
            this.Description_txt.ForeColor = System.Drawing.Color.Black;
            this.Description_txt.HideSelection = true;
            this.Description_txt.IconLeft = null;
            this.Description_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Description_txt.IconPadding = 10;
            this.Description_txt.IconRight = null;
            this.Description_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Description_txt.Lines = new string[0];
            this.Description_txt.Location = new System.Drawing.Point(146, 218);
            this.Description_txt.MaxLength = 32767;
            this.Description_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Description_txt.Modified = false;
            this.Description_txt.Multiline = false;
            this.Description_txt.Name = "Description_txt";
            stateProperties1.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Description_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Description_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Description_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Description_txt.OnIdleState = stateProperties4;
            this.Description_txt.Padding = new System.Windows.Forms.Padding(3);
            this.Description_txt.PasswordChar = '\0';
            this.Description_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Description_txt.PlaceholderText = "Enter Description";
            this.Description_txt.ReadOnly = false;
            this.Description_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Description_txt.SelectedText = "";
            this.Description_txt.SelectionLength = 0;
            this.Description_txt.SelectionStart = 0;
            this.Description_txt.ShortcutsEnabled = true;
            this.Description_txt.Size = new System.Drawing.Size(200, 50);
            this.Description_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Description_txt.TabIndex = 10;
            this.Description_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Description_txt.TextMarginBottom = 0;
            this.Description_txt.TextMarginLeft = 3;
            this.Description_txt.TextMarginTop = 0;
            this.Description_txt.TextPlaceholder = "Enter Description";
            this.Description_txt.UseSystemPasswordChar = false;
            this.Description_txt.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(13, 169);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(77, 23);
            this.label3.TabIndex = 9;
            this.label3.Text = "Name :";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(13, 100);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(43, 23);
            this.label2.TabIndex = 8;
            this.label2.Text = "ID :";
            // 
            // catName_txt
            // 
            this.catName_txt.AcceptsReturn = false;
            this.catName_txt.AcceptsTab = false;
            this.catName_txt.AnimationSpeed = 200;
            this.catName_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.catName_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.catName_txt.BackColor = System.Drawing.Color.White;
            this.catName_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("catName_txt.BackgroundImage")));
            this.catName_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.catName_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.catName_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.catName_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.catName_txt.BorderRadius = 5;
            this.catName_txt.BorderThickness = 3;
            this.catName_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.catName_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.catName_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.catName_txt.DefaultText = "";
            this.catName_txt.FillColor = System.Drawing.Color.White;
            this.catName_txt.ForeColor = System.Drawing.Color.Black;
            this.catName_txt.HideSelection = true;
            this.catName_txt.IconLeft = null;
            this.catName_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.catName_txt.IconPadding = 10;
            this.catName_txt.IconRight = null;
            this.catName_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.catName_txt.Lines = new string[0];
            this.catName_txt.Location = new System.Drawing.Point(146, 152);
            this.catName_txt.MaxLength = 32767;
            this.catName_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.catName_txt.Modified = false;
            this.catName_txt.Multiline = false;
            this.catName_txt.Name = "catName_txt";
            stateProperties5.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catName_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.catName_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catName_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catName_txt.OnIdleState = stateProperties8;
            this.catName_txt.Padding = new System.Windows.Forms.Padding(3);
            this.catName_txt.PasswordChar = '\0';
            this.catName_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.catName_txt.PlaceholderText = "Enter Name";
            this.catName_txt.ReadOnly = false;
            this.catName_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.catName_txt.SelectedText = "";
            this.catName_txt.SelectionLength = 0;
            this.catName_txt.SelectionStart = 0;
            this.catName_txt.ShortcutsEnabled = true;
            this.catName_txt.Size = new System.Drawing.Size(200, 50);
            this.catName_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.catName_txt.TabIndex = 7;
            this.catName_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.catName_txt.TextMarginBottom = 0;
            this.catName_txt.TextMarginLeft = 3;
            this.catName_txt.TextMarginTop = 0;
            this.catName_txt.TextPlaceholder = "Enter Name";
            this.catName_txt.UseSystemPasswordChar = false;
            this.catName_txt.WordWrap = true;
            this.catName_txt.TextChanged += new System.EventHandler(this.catName_txt_TextChanged);
            // 
            // catID_txt
            // 
            this.catID_txt.AcceptsReturn = false;
            this.catID_txt.AcceptsTab = false;
            this.catID_txt.AnimationSpeed = 200;
            this.catID_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.catID_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.catID_txt.BackColor = System.Drawing.Color.White;
            this.catID_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("catID_txt.BackgroundImage")));
            this.catID_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.catID_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.catID_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.catID_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.catID_txt.BorderRadius = 5;
            this.catID_txt.BorderThickness = 3;
            this.catID_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.catID_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.catID_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.catID_txt.DefaultText = "";
            this.catID_txt.FillColor = System.Drawing.Color.White;
            this.catID_txt.ForeColor = System.Drawing.Color.Black;
            this.catID_txt.HideSelection = true;
            this.catID_txt.IconLeft = null;
            this.catID_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.catID_txt.IconPadding = 10;
            this.catID_txt.IconRight = null;
            this.catID_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.catID_txt.Lines = new string[0];
            this.catID_txt.Location = new System.Drawing.Point(146, 84);
            this.catID_txt.MaxLength = 32767;
            this.catID_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.catID_txt.Modified = false;
            this.catID_txt.Multiline = false;
            this.catID_txt.Name = "catID_txt";
            stateProperties9.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catID_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.catID_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catID_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.catID_txt.OnIdleState = stateProperties12;
            this.catID_txt.Padding = new System.Windows.Forms.Padding(3);
            this.catID_txt.PasswordChar = '\0';
            this.catID_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.catID_txt.PlaceholderText = "Enter ID";
            this.catID_txt.ReadOnly = false;
            this.catID_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.catID_txt.SelectedText = "";
            this.catID_txt.SelectionLength = 0;
            this.catID_txt.SelectionStart = 0;
            this.catID_txt.ShortcutsEnabled = true;
            this.catID_txt.Size = new System.Drawing.Size(200, 50);
            this.catID_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.catID_txt.TabIndex = 6;
            this.catID_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.catID_txt.TextMarginBottom = 0;
            this.catID_txt.TextMarginLeft = 3;
            this.catID_txt.TextMarginTop = 0;
            this.catID_txt.TextPlaceholder = "Enter ID";
            this.catID_txt.UseSystemPasswordChar = false;
            this.catID_txt.WordWrap = true;
            // 
            // Product_btn
            // 
            this.Product_btn.ActiveBorderThickness = 2;
            this.Product_btn.ActiveCornerRadius = 20;
            this.Product_btn.ActiveFillColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.ActiveForecolor = System.Drawing.Color.White;
            this.Product_btn.ActiveLineColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.BackColor = System.Drawing.Color.White;
            this.Product_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Product_btn.BackgroundImage")));
            this.Product_btn.ButtonText = "Products";
            this.Product_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Product_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Product_btn.ForeColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.IdleBorderThickness = 2;
            this.Product_btn.IdleCornerRadius = 20;
            this.Product_btn.IdleFillColor = System.Drawing.Color.White;
            this.Product_btn.IdleForecolor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.IdleLineColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.Location = new System.Drawing.Point(14, 180);
            this.Product_btn.Margin = new System.Windows.Forms.Padding(5);
            this.Product_btn.Name = "Product_btn";
            this.Product_btn.Size = new System.Drawing.Size(156, 56);
            this.Product_btn.TabIndex = 22;
            this.Product_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Product_btn.Click += new System.EventHandler(this.Product_btn_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.panel1.Controls.Add(this.Categories_grid);
            this.panel1.Controls.Add(this.Refresh_btn);
            this.panel1.Controls.Add(this.label6);
            this.panel1.Controls.Add(this.Delete_btn);
            this.panel1.Controls.Add(this.Edit_btn);
            this.panel1.Controls.Add(this.Add_btn);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.Description_txt);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.catName_txt);
            this.panel1.Controls.Add(this.catID_txt);
            this.panel1.Location = new System.Drawing.Point(178, 36);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1010, 602);
            this.panel1.TabIndex = 19;
            // 
            // Categories_grid
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.Categories_grid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(88)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.Categories_grid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.Categories_grid.ColumnHeadersHeight = 20;
            this.Categories_grid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Century", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.Categories_grid.DefaultCellStyle = dataGridViewCellStyle3;
            this.Categories_grid.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Categories_grid.Location = new System.Drawing.Point(366, 121);
            this.Categories_grid.Name = "Categories_grid";
            this.Categories_grid.RowTemplate.Height = 35;
            this.Categories_grid.Size = new System.Drawing.Size(626, 465);
            this.Categories_grid.TabIndex = 22;
            this.Categories_grid.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.Categories_grid.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.Categories_grid.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.Categories_grid.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.Categories_grid.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.Categories_grid.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.Categories_grid.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Categories_grid.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.Categories_grid.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.Categories_grid.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F);
            this.Categories_grid.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.Categories_grid.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            this.Categories_grid.ThemeStyle.HeaderStyle.Height = 20;
            this.Categories_grid.ThemeStyle.ReadOnly = false;
            this.Categories_grid.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.Categories_grid.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.Categories_grid.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Categories_grid.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.Categories_grid.ThemeStyle.RowsStyle.Height = 35;
            this.Categories_grid.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Categories_grid.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.Categories_grid.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Categories_grid_CellContentClick);
            // 
            // logout
            // 
            this.logout.AutoSize = true;
            this.logout.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.logout.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.logout.Location = new System.Drawing.Point(51, 615);
            this.logout.Name = "logout";
            this.logout.Size = new System.Drawing.Size(76, 23);
            this.logout.TabIndex = 26;
            this.logout.Text = "Logout";
            this.logout.Click += new System.EventHandler(this.logout_Click);
            // 
            // Categories
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1200, 650);
            this.Controls.Add(this.logout);
            this.Controls.Add(this.Seller_btn);
            this.Controls.Add(this.close);
            this.Controls.Add(this.Product_btn);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Categories";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Categories";
            this.Load += new System.EventHandler(this.Categories_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Categories_grid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Refresh_btn;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Delete_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Add_btn;
        private Bunifu.Framework.UI.BunifuThinButton2 Seller_btn;
        private System.Windows.Forms.Label close;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox Description_txt;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox catName_txt;
        private Bunifu.UI.WinForms.BunifuTextBox catID_txt;
        private Bunifu.Framework.UI.BunifuThinButton2 Product_btn;
        private System.Windows.Forms.Panel panel1;
        private Guna.UI2.WinForms.Guna2DataGridView Categories_grid;
        private System.Windows.Forms.Label logout;
    }
}