namespace SuperMarket
{
    partial class Seller
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Seller));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Category_btn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.Product_btn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.close = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label5 = new System.Windows.Forms.Label();
            this.sellerPassoword_set_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Seller_grid = new Guna.UI2.WinForms.Guna2DataGridView();
            this.Refresh_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label6 = new System.Windows.Forms.Label();
            this.Delete_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Edit_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Add_btn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.sellerPhone_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.sellerAge_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.sellerName_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.sellerID_txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.logout = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Seller_grid)).BeginInit();
            this.SuspendLayout();
            // 
            // Category_btn
            // 
            this.Category_btn.ActiveBorderThickness = 2;
            this.Category_btn.ActiveCornerRadius = 20;
            this.Category_btn.ActiveFillColor = System.Drawing.Color.DodgerBlue;
            this.Category_btn.ActiveForecolor = System.Drawing.Color.White;
            this.Category_btn.ActiveLineColor = System.Drawing.Color.DodgerBlue;
            this.Category_btn.BackColor = System.Drawing.Color.White;
            this.Category_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Category_btn.BackgroundImage")));
            this.Category_btn.ButtonText = "Categories";
            this.Category_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Category_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Category_btn.ForeColor = System.Drawing.Color.DodgerBlue;
            this.Category_btn.IdleBorderThickness = 2;
            this.Category_btn.IdleCornerRadius = 20;
            this.Category_btn.IdleFillColor = System.Drawing.Color.White;
            this.Category_btn.IdleForecolor = System.Drawing.Color.DodgerBlue;
            this.Category_btn.IdleLineColor = System.Drawing.Color.DodgerBlue;
            this.Category_btn.Location = new System.Drawing.Point(13, 181);
            this.Category_btn.Margin = new System.Windows.Forms.Padding(5);
            this.Category_btn.Name = "Category_btn";
            this.Category_btn.Size = new System.Drawing.Size(156, 56);
            this.Category_btn.TabIndex = 22;
            this.Category_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Category_btn.Click += new System.EventHandler(this.Category_btn_Click);
            // 
            // Product_btn
            // 
            this.Product_btn.ActiveBorderThickness = 2;
            this.Product_btn.ActiveCornerRadius = 20;
            this.Product_btn.ActiveFillColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.ActiveForecolor = System.Drawing.Color.White;
            this.Product_btn.ActiveLineColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.BackColor = System.Drawing.Color.White;
            this.Product_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Product_btn.BackgroundImage")));
            this.Product_btn.ButtonText = "Products";
            this.Product_btn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Product_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Product_btn.ForeColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.IdleBorderThickness = 2;
            this.Product_btn.IdleCornerRadius = 20;
            this.Product_btn.IdleFillColor = System.Drawing.Color.White;
            this.Product_btn.IdleForecolor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.IdleLineColor = System.Drawing.Color.DodgerBlue;
            this.Product_btn.Location = new System.Drawing.Point(13, 115);
            this.Product_btn.Margin = new System.Windows.Forms.Padding(5);
            this.Product_btn.Name = "Product_btn";
            this.Product_btn.Size = new System.Drawing.Size(156, 56);
            this.Product_btn.TabIndex = 21;
            this.Product_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Product_btn.Click += new System.EventHandler(this.Product_btn_Click);
            // 
            // close
            // 
            this.close.AutoSize = true;
            this.close.BackColor = System.Drawing.Color.DodgerBlue;
            this.close.Font = new System.Drawing.Font("Leelawadee", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.close.ForeColor = System.Drawing.Color.White;
            this.close.Location = new System.Drawing.Point(1166, 10);
            this.close.Name = "close";
            this.close.Size = new System.Drawing.Size(21, 23);
            this.close.TabIndex = 20;
            this.close.Text = "x";
            this.close.Click += new System.EventHandler(this.close_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.panel1.Controls.Add(this.label5);
            this.panel1.Controls.Add(this.sellerPassoword_set_txt);
            this.panel1.Controls.Add(this.Seller_grid);
            this.panel1.Controls.Add(this.Refresh_btn);
            this.panel1.Controls.Add(this.label6);
            this.panel1.Controls.Add(this.Delete_btn);
            this.panel1.Controls.Add(this.Edit_btn);
            this.panel1.Controls.Add(this.Add_btn);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.label4);
            this.panel1.Controls.Add(this.sellerPhone_txt);
            this.panel1.Controls.Add(this.sellerAge_txt);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.sellerName_txt);
            this.panel1.Controls.Add(this.sellerID_txt);
            this.panel1.Location = new System.Drawing.Point(177, 37);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1010, 602);
            this.panel1.TabIndex = 19;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(13, 372);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(114, 23);
            this.label5.TabIndex = 24;
            this.label5.Text = "Password :";
            // 
            // sellerPassoword_set_txt
            // 
            this.sellerPassoword_set_txt.AcceptsReturn = false;
            this.sellerPassoword_set_txt.AcceptsTab = false;
            this.sellerPassoword_set_txt.AnimationSpeed = 200;
            this.sellerPassoword_set_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sellerPassoword_set_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sellerPassoword_set_txt.BackColor = System.Drawing.Color.White;
            this.sellerPassoword_set_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sellerPassoword_set_txt.BackgroundImage")));
            this.sellerPassoword_set_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.sellerPassoword_set_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sellerPassoword_set_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sellerPassoword_set_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.sellerPassoword_set_txt.BorderRadius = 5;
            this.sellerPassoword_set_txt.BorderThickness = 3;
            this.sellerPassoword_set_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sellerPassoword_set_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPassoword_set_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellerPassoword_set_txt.DefaultText = "";
            this.sellerPassoword_set_txt.FillColor = System.Drawing.Color.White;
            this.sellerPassoword_set_txt.ForeColor = System.Drawing.Color.Black;
            this.sellerPassoword_set_txt.HideSelection = true;
            this.sellerPassoword_set_txt.IconLeft = null;
            this.sellerPassoword_set_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPassoword_set_txt.IconPadding = 10;
            this.sellerPassoword_set_txt.IconRight = null;
            this.sellerPassoword_set_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPassoword_set_txt.Lines = new string[0];
            this.sellerPassoword_set_txt.Location = new System.Drawing.Point(140, 355);
            this.sellerPassoword_set_txt.MaxLength = 32767;
            this.sellerPassoword_set_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sellerPassoword_set_txt.Modified = false;
            this.sellerPassoword_set_txt.Multiline = false;
            this.sellerPassoword_set_txt.Name = "sellerPassoword_set_txt";
            stateProperties1.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPassoword_set_txt.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sellerPassoword_set_txt.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPassoword_set_txt.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPassoword_set_txt.OnIdleState = stateProperties4;
            this.sellerPassoword_set_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sellerPassoword_set_txt.PasswordChar = '\0';
            this.sellerPassoword_set_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.sellerPassoword_set_txt.PlaceholderText = "Enter Passoword";
            this.sellerPassoword_set_txt.ReadOnly = false;
            this.sellerPassoword_set_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sellerPassoword_set_txt.SelectedText = "";
            this.sellerPassoword_set_txt.SelectionLength = 0;
            this.sellerPassoword_set_txt.SelectionStart = 0;
            this.sellerPassoword_set_txt.ShortcutsEnabled = true;
            this.sellerPassoword_set_txt.Size = new System.Drawing.Size(200, 50);
            this.sellerPassoword_set_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sellerPassoword_set_txt.TabIndex = 23;
            this.sellerPassoword_set_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sellerPassoword_set_txt.TextMarginBottom = 0;
            this.sellerPassoword_set_txt.TextMarginLeft = 3;
            this.sellerPassoword_set_txt.TextMarginTop = 0;
            this.sellerPassoword_set_txt.TextPlaceholder = "Enter Passoword";
            this.sellerPassoword_set_txt.UseSystemPasswordChar = false;
            this.sellerPassoword_set_txt.WordWrap = true;
            // 
            // Seller_grid
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.Seller_grid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(88)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.Seller_grid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.Seller_grid.ColumnHeadersHeight = 20;
            this.Seller_grid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.Seller_grid.DefaultCellStyle = dataGridViewCellStyle3;
            this.Seller_grid.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Seller_grid.Location = new System.Drawing.Point(366, 120);
            this.Seller_grid.Name = "Seller_grid";
            this.Seller_grid.RowHeadersVisible = false;
            this.Seller_grid.Size = new System.Drawing.Size(626, 465);
            this.Seller_grid.TabIndex = 22;
            this.Seller_grid.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.Color.White;
            this.Seller_grid.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.Seller_grid.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.Seller_grid.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.Seller_grid.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.Seller_grid.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.Seller_grid.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Seller_grid.ThemeStyle.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(88)))), ((int)(((byte)(255)))));
            this.Seller_grid.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.Seller_grid.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Seller_grid.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.Seller_grid.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            this.Seller_grid.ThemeStyle.HeaderStyle.Height = 20;
            this.Seller_grid.ThemeStyle.ReadOnly = false;
            this.Seller_grid.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.Seller_grid.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.Seller_grid.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Century", 15.75F, System.Drawing.FontStyle.Bold);
            this.Seller_grid.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.Seller_grid.ThemeStyle.RowsStyle.Height = 22;
            this.Seller_grid.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.Seller_grid.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.Seller_grid.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Seller_grid_CellContentClick);
            // 
            // Refresh_btn
            // 
            this.Refresh_btn.AllowAnimations = true;
            this.Refresh_btn.AllowMouseEffects = true;
            this.Refresh_btn.AllowToggling = false;
            this.Refresh_btn.AnimationSpeed = 200;
            this.Refresh_btn.AutoGenerateColors = false;
            this.Refresh_btn.AutoRoundBorders = false;
            this.Refresh_btn.AutoSizeLeftIcon = true;
            this.Refresh_btn.AutoSizeRightIcon = true;
            this.Refresh_btn.BackColor = System.Drawing.Color.Transparent;
            this.Refresh_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Refresh_btn.BackgroundImage")));
            this.Refresh_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.ButtonText = "Refresh";
            this.Refresh_btn.ButtonTextMarginLeft = 0;
            this.Refresh_btn.ColorContrastOnClick = 45;
            this.Refresh_btn.ColorContrastOnHover = 45;
            this.Refresh_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Refresh_btn.CustomizableEdges = borderEdges1;
            this.Refresh_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Refresh_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Refresh_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Refresh_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Refresh_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Refresh_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Refresh_btn.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Refresh_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Refresh_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Refresh_btn.IconMarginLeft = 11;
            this.Refresh_btn.IconPadding = 10;
            this.Refresh_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Refresh_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Refresh_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Refresh_btn.IconSize = 25;
            this.Refresh_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Refresh_btn.IdleBorderRadius = 3;
            this.Refresh_btn.IdleBorderThickness = 2;
            this.Refresh_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.IdleIconLeftImage = null;
            this.Refresh_btn.IdleIconRightImage = null;
            this.Refresh_btn.IndicateFocus = false;
            this.Refresh_btn.Location = new System.Drawing.Point(891, 69);
            this.Refresh_btn.Name = "Refresh_btn";
            this.Refresh_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Refresh_btn.OnDisabledState.BorderRadius = 3;
            this.Refresh_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnDisabledState.BorderThickness = 2;
            this.Refresh_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Refresh_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Refresh_btn.OnDisabledState.IconLeftImage = null;
            this.Refresh_btn.OnDisabledState.IconRightImage = null;
            this.Refresh_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Refresh_btn.onHoverState.BorderRadius = 3;
            this.Refresh_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.onHoverState.BorderThickness = 2;
            this.Refresh_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Refresh_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Refresh_btn.onHoverState.IconLeftImage = null;
            this.Refresh_btn.onHoverState.IconRightImage = null;
            this.Refresh_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Refresh_btn.OnIdleState.BorderRadius = 3;
            this.Refresh_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnIdleState.BorderThickness = 2;
            this.Refresh_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Refresh_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.OnIdleState.IconLeftImage = null;
            this.Refresh_btn.OnIdleState.IconRightImage = null;
            this.Refresh_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Refresh_btn.OnPressedState.BorderRadius = 3;
            this.Refresh_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Refresh_btn.OnPressedState.BorderThickness = 2;
            this.Refresh_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Refresh_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Refresh_btn.OnPressedState.IconLeftImage = null;
            this.Refresh_btn.OnPressedState.IconRightImage = null;
            this.Refresh_btn.Size = new System.Drawing.Size(102, 46);
            this.Refresh_btn.TabIndex = 20;
            this.Refresh_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Refresh_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Refresh_btn.TextMarginLeft = 0;
            this.Refresh_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Refresh_btn.UseDefaultRadiusAndThickness = true;
            this.Refresh_btn.Click += new System.EventHandler(this.Refresh_btn_Click);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.label6.Font = new System.Drawing.Font("Century Gothic", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(377, 10);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(275, 41);
            this.label6.TabIndex = 19;
            this.label6.Text = "Manage Sellers";
            this.label6.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // Delete_btn
            // 
            this.Delete_btn.AllowAnimations = true;
            this.Delete_btn.AllowMouseEffects = true;
            this.Delete_btn.AllowToggling = false;
            this.Delete_btn.AnimationSpeed = 200;
            this.Delete_btn.AutoGenerateColors = false;
            this.Delete_btn.AutoRoundBorders = false;
            this.Delete_btn.AutoSizeLeftIcon = true;
            this.Delete_btn.AutoSizeRightIcon = true;
            this.Delete_btn.BackColor = System.Drawing.Color.Transparent;
            this.Delete_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delete_btn.BackgroundImage")));
            this.Delete_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.ButtonText = "Delete";
            this.Delete_btn.ButtonTextMarginLeft = 0;
            this.Delete_btn.ColorContrastOnClick = 45;
            this.Delete_btn.ColorContrastOnHover = 45;
            this.Delete_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Delete_btn.CustomizableEdges = borderEdges2;
            this.Delete_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Delete_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Delete_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Delete_btn.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Delete_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Delete_btn.IconMarginLeft = 11;
            this.Delete_btn.IconPadding = 10;
            this.Delete_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Delete_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Delete_btn.IconSize = 25;
            this.Delete_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Delete_btn.IdleBorderRadius = 3;
            this.Delete_btn.IdleBorderThickness = 2;
            this.Delete_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.IdleIconLeftImage = null;
            this.Delete_btn.IdleIconRightImage = null;
            this.Delete_btn.IndicateFocus = false;
            this.Delete_btn.Location = new System.Drawing.Point(248, 429);
            this.Delete_btn.Name = "Delete_btn";
            this.Delete_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn.OnDisabledState.BorderRadius = 3;
            this.Delete_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnDisabledState.BorderThickness = 2;
            this.Delete_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn.OnDisabledState.IconLeftImage = null;
            this.Delete_btn.OnDisabledState.IconRightImage = null;
            this.Delete_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Delete_btn.onHoverState.BorderRadius = 3;
            this.Delete_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.onHoverState.BorderThickness = 2;
            this.Delete_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Delete_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Delete_btn.onHoverState.IconLeftImage = null;
            this.Delete_btn.onHoverState.IconRightImage = null;
            this.Delete_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Delete_btn.OnIdleState.BorderRadius = 3;
            this.Delete_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnIdleState.BorderThickness = 2;
            this.Delete_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Delete_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.OnIdleState.IconLeftImage = null;
            this.Delete_btn.OnIdleState.IconRightImage = null;
            this.Delete_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn.OnPressedState.BorderRadius = 3;
            this.Delete_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Delete_btn.OnPressedState.BorderThickness = 2;
            this.Delete_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn.OnPressedState.IconLeftImage = null;
            this.Delete_btn.OnPressedState.IconRightImage = null;
            this.Delete_btn.Size = new System.Drawing.Size(102, 46);
            this.Delete_btn.TabIndex = 18;
            this.Delete_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Delete_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Delete_btn.TextMarginLeft = 0;
            this.Delete_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Delete_btn.UseDefaultRadiusAndThickness = true;
            this.Delete_btn.Click += new System.EventHandler(this.Delete_btn_Click);
            // 
            // Edit_btn
            // 
            this.Edit_btn.AllowAnimations = true;
            this.Edit_btn.AllowMouseEffects = true;
            this.Edit_btn.AllowToggling = false;
            this.Edit_btn.AnimationSpeed = 200;
            this.Edit_btn.AutoGenerateColors = false;
            this.Edit_btn.AutoRoundBorders = false;
            this.Edit_btn.AutoSizeLeftIcon = true;
            this.Edit_btn.AutoSizeRightIcon = true;
            this.Edit_btn.BackColor = System.Drawing.Color.Transparent;
            this.Edit_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Edit_btn.BackgroundImage")));
            this.Edit_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.ButtonText = "Edit";
            this.Edit_btn.ButtonTextMarginLeft = 0;
            this.Edit_btn.ColorContrastOnClick = 45;
            this.Edit_btn.ColorContrastOnHover = 45;
            this.Edit_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Edit_btn.CustomizableEdges = borderEdges3;
            this.Edit_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Edit_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Edit_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Edit_btn.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Edit_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Edit_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Edit_btn.IconMarginLeft = 11;
            this.Edit_btn.IconPadding = 10;
            this.Edit_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Edit_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Edit_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Edit_btn.IconSize = 25;
            this.Edit_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Edit_btn.IdleBorderRadius = 3;
            this.Edit_btn.IdleBorderThickness = 2;
            this.Edit_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.IdleIconLeftImage = null;
            this.Edit_btn.IdleIconRightImage = null;
            this.Edit_btn.IndicateFocus = false;
            this.Edit_btn.Location = new System.Drawing.Point(131, 429);
            this.Edit_btn.Name = "Edit_btn";
            this.Edit_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Edit_btn.OnDisabledState.BorderRadius = 3;
            this.Edit_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnDisabledState.BorderThickness = 2;
            this.Edit_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Edit_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Edit_btn.OnDisabledState.IconLeftImage = null;
            this.Edit_btn.OnDisabledState.IconRightImage = null;
            this.Edit_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Edit_btn.onHoverState.BorderRadius = 3;
            this.Edit_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.onHoverState.BorderThickness = 2;
            this.Edit_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Edit_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Edit_btn.onHoverState.IconLeftImage = null;
            this.Edit_btn.onHoverState.IconRightImage = null;
            this.Edit_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Edit_btn.OnIdleState.BorderRadius = 3;
            this.Edit_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnIdleState.BorderThickness = 2;
            this.Edit_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Edit_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.OnIdleState.IconLeftImage = null;
            this.Edit_btn.OnIdleState.IconRightImage = null;
            this.Edit_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit_btn.OnPressedState.BorderRadius = 3;
            this.Edit_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Edit_btn.OnPressedState.BorderThickness = 2;
            this.Edit_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Edit_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Edit_btn.OnPressedState.IconLeftImage = null;
            this.Edit_btn.OnPressedState.IconRightImage = null;
            this.Edit_btn.Size = new System.Drawing.Size(102, 46);
            this.Edit_btn.TabIndex = 17;
            this.Edit_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Edit_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Edit_btn.TextMarginLeft = 0;
            this.Edit_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Edit_btn.UseDefaultRadiusAndThickness = true;
            this.Edit_btn.Click += new System.EventHandler(this.Edit_btn_Click);
            // 
            // Add_btn
            // 
            this.Add_btn.AllowAnimations = true;
            this.Add_btn.AllowMouseEffects = true;
            this.Add_btn.AllowToggling = false;
            this.Add_btn.AnimationSpeed = 200;
            this.Add_btn.AutoGenerateColors = false;
            this.Add_btn.AutoRoundBorders = false;
            this.Add_btn.AutoSizeLeftIcon = true;
            this.Add_btn.AutoSizeRightIcon = true;
            this.Add_btn.BackColor = System.Drawing.Color.Transparent;
            this.Add_btn.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Add_btn.BackgroundImage")));
            this.Add_btn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.ButtonText = "Add";
            this.Add_btn.ButtonTextMarginLeft = 0;
            this.Add_btn.ColorContrastOnClick = 45;
            this.Add_btn.ColorContrastOnHover = 45;
            this.Add_btn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Add_btn.CustomizableEdges = borderEdges4;
            this.Add_btn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Add_btn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Add_btn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Add_btn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Add_btn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Add_btn.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.Add_btn.ForeColor = System.Drawing.Color.White;
            this.Add_btn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Add_btn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Add_btn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Add_btn.IconMarginLeft = 11;
            this.Add_btn.IconPadding = 10;
            this.Add_btn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Add_btn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Add_btn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Add_btn.IconSize = 25;
            this.Add_btn.IdleBorderColor = System.Drawing.Color.White;
            this.Add_btn.IdleBorderRadius = 3;
            this.Add_btn.IdleBorderThickness = 2;
            this.Add_btn.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.IdleIconLeftImage = null;
            this.Add_btn.IdleIconRightImage = null;
            this.Add_btn.IndicateFocus = false;
            this.Add_btn.Location = new System.Drawing.Point(14, 429);
            this.Add_btn.Name = "Add_btn";
            this.Add_btn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Add_btn.OnDisabledState.BorderRadius = 3;
            this.Add_btn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnDisabledState.BorderThickness = 2;
            this.Add_btn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Add_btn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Add_btn.OnDisabledState.IconLeftImage = null;
            this.Add_btn.OnDisabledState.IconRightImage = null;
            this.Add_btn.onHoverState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.Add_btn.onHoverState.BorderRadius = 3;
            this.Add_btn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.onHoverState.BorderThickness = 2;
            this.Add_btn.onHoverState.FillColor = System.Drawing.Color.White;
            this.Add_btn.onHoverState.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.Add_btn.onHoverState.IconLeftImage = null;
            this.Add_btn.onHoverState.IconRightImage = null;
            this.Add_btn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.Add_btn.OnIdleState.BorderRadius = 3;
            this.Add_btn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnIdleState.BorderThickness = 2;
            this.Add_btn.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.Add_btn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Add_btn.OnIdleState.IconLeftImage = null;
            this.Add_btn.OnIdleState.IconRightImage = null;
            this.Add_btn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Add_btn.OnPressedState.BorderRadius = 3;
            this.Add_btn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Add_btn.OnPressedState.BorderThickness = 2;
            this.Add_btn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Add_btn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Add_btn.OnPressedState.IconLeftImage = null;
            this.Add_btn.OnPressedState.IconRightImage = null;
            this.Add_btn.Size = new System.Drawing.Size(102, 46);
            this.Add_btn.TabIndex = 16;
            this.Add_btn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Add_btn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Add_btn.TextMarginLeft = 0;
            this.Add_btn.TextPadding = new System.Windows.Forms.Padding(0);
            this.Add_btn.UseDefaultRadiusAndThickness = true;
            this.Add_btn.Click += new System.EventHandler(this.Add_btn_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(13, 302);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(81, 23);
            this.label1.TabIndex = 13;
            this.label1.Text = "Phone :";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(13, 233);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(61, 23);
            this.label4.TabIndex = 12;
            this.label4.Text = "Age :";
            // 
            // sellerPhone_txt
            // 
            this.sellerPhone_txt.AcceptsReturn = false;
            this.sellerPhone_txt.AcceptsTab = false;
            this.sellerPhone_txt.AnimationSpeed = 200;
            this.sellerPhone_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sellerPhone_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sellerPhone_txt.BackColor = System.Drawing.Color.White;
            this.sellerPhone_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sellerPhone_txt.BackgroundImage")));
            this.sellerPhone_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.sellerPhone_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sellerPhone_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sellerPhone_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.sellerPhone_txt.BorderRadius = 5;
            this.sellerPhone_txt.BorderThickness = 3;
            this.sellerPhone_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sellerPhone_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPhone_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellerPhone_txt.DefaultText = "";
            this.sellerPhone_txt.FillColor = System.Drawing.Color.White;
            this.sellerPhone_txt.ForeColor = System.Drawing.Color.Black;
            this.sellerPhone_txt.HideSelection = true;
            this.sellerPhone_txt.IconLeft = null;
            this.sellerPhone_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPhone_txt.IconPadding = 10;
            this.sellerPhone_txt.IconRight = null;
            this.sellerPhone_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerPhone_txt.Lines = new string[0];
            this.sellerPhone_txt.Location = new System.Drawing.Point(140, 285);
            this.sellerPhone_txt.MaxLength = 32767;
            this.sellerPhone_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sellerPhone_txt.Modified = false;
            this.sellerPhone_txt.Multiline = false;
            this.sellerPhone_txt.Name = "sellerPhone_txt";
            stateProperties5.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPhone_txt.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sellerPhone_txt.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPhone_txt.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerPhone_txt.OnIdleState = stateProperties8;
            this.sellerPhone_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sellerPhone_txt.PasswordChar = '\0';
            this.sellerPhone_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.sellerPhone_txt.PlaceholderText = "Enter Phone Number";
            this.sellerPhone_txt.ReadOnly = false;
            this.sellerPhone_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sellerPhone_txt.SelectedText = "";
            this.sellerPhone_txt.SelectionLength = 0;
            this.sellerPhone_txt.SelectionStart = 0;
            this.sellerPhone_txt.ShortcutsEnabled = true;
            this.sellerPhone_txt.Size = new System.Drawing.Size(200, 50);
            this.sellerPhone_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sellerPhone_txt.TabIndex = 11;
            this.sellerPhone_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sellerPhone_txt.TextMarginBottom = 0;
            this.sellerPhone_txt.TextMarginLeft = 3;
            this.sellerPhone_txt.TextMarginTop = 0;
            this.sellerPhone_txt.TextPlaceholder = "Enter Phone Number";
            this.sellerPhone_txt.UseSystemPasswordChar = false;
            this.sellerPhone_txt.WordWrap = true;
            // 
            // sellerAge_txt
            // 
            this.sellerAge_txt.AcceptsReturn = false;
            this.sellerAge_txt.AcceptsTab = false;
            this.sellerAge_txt.AnimationSpeed = 200;
            this.sellerAge_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sellerAge_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sellerAge_txt.BackColor = System.Drawing.Color.White;
            this.sellerAge_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sellerAge_txt.BackgroundImage")));
            this.sellerAge_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.sellerAge_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sellerAge_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sellerAge_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.sellerAge_txt.BorderRadius = 5;
            this.sellerAge_txt.BorderThickness = 3;
            this.sellerAge_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sellerAge_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerAge_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellerAge_txt.DefaultText = "";
            this.sellerAge_txt.FillColor = System.Drawing.Color.White;
            this.sellerAge_txt.ForeColor = System.Drawing.Color.Black;
            this.sellerAge_txt.HideSelection = true;
            this.sellerAge_txt.IconLeft = null;
            this.sellerAge_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerAge_txt.IconPadding = 10;
            this.sellerAge_txt.IconRight = null;
            this.sellerAge_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerAge_txt.Lines = new string[0];
            this.sellerAge_txt.Location = new System.Drawing.Point(140, 217);
            this.sellerAge_txt.MaxLength = 32767;
            this.sellerAge_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sellerAge_txt.Modified = false;
            this.sellerAge_txt.Multiline = false;
            this.sellerAge_txt.Name = "sellerAge_txt";
            stateProperties9.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerAge_txt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sellerAge_txt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerAge_txt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerAge_txt.OnIdleState = stateProperties12;
            this.sellerAge_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sellerAge_txt.PasswordChar = '\0';
            this.sellerAge_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.sellerAge_txt.PlaceholderText = "Enter Age";
            this.sellerAge_txt.ReadOnly = false;
            this.sellerAge_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sellerAge_txt.SelectedText = "";
            this.sellerAge_txt.SelectionLength = 0;
            this.sellerAge_txt.SelectionStart = 0;
            this.sellerAge_txt.ShortcutsEnabled = true;
            this.sellerAge_txt.Size = new System.Drawing.Size(200, 50);
            this.sellerAge_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sellerAge_txt.TabIndex = 10;
            this.sellerAge_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sellerAge_txt.TextMarginBottom = 0;
            this.sellerAge_txt.TextMarginLeft = 3;
            this.sellerAge_txt.TextMarginTop = 0;
            this.sellerAge_txt.TextPlaceholder = "Enter Age";
            this.sellerAge_txt.UseSystemPasswordChar = false;
            this.sellerAge_txt.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(13, 168);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(77, 23);
            this.label3.TabIndex = 9;
            this.label3.Text = "Name :";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(13, 99);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(43, 23);
            this.label2.TabIndex = 8;
            this.label2.Text = "ID :";
            // 
            // sellerName_txt
            // 
            this.sellerName_txt.AcceptsReturn = false;
            this.sellerName_txt.AcceptsTab = false;
            this.sellerName_txt.AnimationSpeed = 200;
            this.sellerName_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sellerName_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sellerName_txt.BackColor = System.Drawing.Color.White;
            this.sellerName_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sellerName_txt.BackgroundImage")));
            this.sellerName_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.sellerName_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sellerName_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sellerName_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.sellerName_txt.BorderRadius = 5;
            this.sellerName_txt.BorderThickness = 3;
            this.sellerName_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sellerName_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerName_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellerName_txt.DefaultText = "";
            this.sellerName_txt.FillColor = System.Drawing.Color.White;
            this.sellerName_txt.ForeColor = System.Drawing.Color.Black;
            this.sellerName_txt.HideSelection = true;
            this.sellerName_txt.IconLeft = null;
            this.sellerName_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerName_txt.IconPadding = 10;
            this.sellerName_txt.IconRight = null;
            this.sellerName_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerName_txt.Lines = new string[0];
            this.sellerName_txt.Location = new System.Drawing.Point(140, 151);
            this.sellerName_txt.MaxLength = 32767;
            this.sellerName_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sellerName_txt.Modified = false;
            this.sellerName_txt.Multiline = false;
            this.sellerName_txt.Name = "sellerName_txt";
            stateProperties13.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerName_txt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sellerName_txt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerName_txt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerName_txt.OnIdleState = stateProperties16;
            this.sellerName_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sellerName_txt.PasswordChar = '\0';
            this.sellerName_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.sellerName_txt.PlaceholderText = "Enter Name";
            this.sellerName_txt.ReadOnly = false;
            this.sellerName_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sellerName_txt.SelectedText = "";
            this.sellerName_txt.SelectionLength = 0;
            this.sellerName_txt.SelectionStart = 0;
            this.sellerName_txt.ShortcutsEnabled = true;
            this.sellerName_txt.Size = new System.Drawing.Size(200, 50);
            this.sellerName_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sellerName_txt.TabIndex = 7;
            this.sellerName_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sellerName_txt.TextMarginBottom = 0;
            this.sellerName_txt.TextMarginLeft = 3;
            this.sellerName_txt.TextMarginTop = 0;
            this.sellerName_txt.TextPlaceholder = "Enter Name";
            this.sellerName_txt.UseSystemPasswordChar = false;
            this.sellerName_txt.WordWrap = true;
            // 
            // sellerID_txt
            // 
            this.sellerID_txt.AcceptsReturn = false;
            this.sellerID_txt.AcceptsTab = false;
            this.sellerID_txt.AnimationSpeed = 200;
            this.sellerID_txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.sellerID_txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.sellerID_txt.BackColor = System.Drawing.Color.White;
            this.sellerID_txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sellerID_txt.BackgroundImage")));
            this.sellerID_txt.BorderColorActive = System.Drawing.Color.DeepSkyBlue;
            this.sellerID_txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sellerID_txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.sellerID_txt.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.sellerID_txt.BorderRadius = 5;
            this.sellerID_txt.BorderThickness = 3;
            this.sellerID_txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.sellerID_txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerID_txt.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellerID_txt.DefaultText = "";
            this.sellerID_txt.FillColor = System.Drawing.Color.White;
            this.sellerID_txt.ForeColor = System.Drawing.Color.Black;
            this.sellerID_txt.HideSelection = true;
            this.sellerID_txt.IconLeft = null;
            this.sellerID_txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerID_txt.IconPadding = 10;
            this.sellerID_txt.IconRight = null;
            this.sellerID_txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.sellerID_txt.Lines = new string[0];
            this.sellerID_txt.Location = new System.Drawing.Point(140, 83);
            this.sellerID_txt.MaxLength = 32767;
            this.sellerID_txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.sellerID_txt.Modified = false;
            this.sellerID_txt.Multiline = false;
            this.sellerID_txt.Name = "sellerID_txt";
            stateProperties17.BorderColor = System.Drawing.Color.DeepSkyBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerID_txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.sellerID_txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerID_txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.sellerID_txt.OnIdleState = stateProperties20;
            this.sellerID_txt.Padding = new System.Windows.Forms.Padding(3);
            this.sellerID_txt.PasswordChar = '\0';
            this.sellerID_txt.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.sellerID_txt.PlaceholderText = "Enter ID";
            this.sellerID_txt.ReadOnly = false;
            this.sellerID_txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.sellerID_txt.SelectedText = "";
            this.sellerID_txt.SelectionLength = 0;
            this.sellerID_txt.SelectionStart = 0;
            this.sellerID_txt.ShortcutsEnabled = true;
            this.sellerID_txt.Size = new System.Drawing.Size(200, 50);
            this.sellerID_txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.sellerID_txt.TabIndex = 6;
            this.sellerID_txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.sellerID_txt.TextMarginBottom = 0;
            this.sellerID_txt.TextMarginLeft = 3;
            this.sellerID_txt.TextMarginTop = 0;
            this.sellerID_txt.TextPlaceholder = "Enter ID";
            this.sellerID_txt.UseSystemPasswordChar = false;
            this.sellerID_txt.WordWrap = true;
            // 
            // logout
            // 
            this.logout.AutoSize = true;
            this.logout.Font = new System.Drawing.Font("Rockwell", 15.75F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.logout.ForeColor = System.Drawing.Color.DeepSkyBlue;
            this.logout.Location = new System.Drawing.Point(51, 615);
            this.logout.Name = "logout";
            this.logout.Size = new System.Drawing.Size(76, 23);
            this.logout.TabIndex = 26;
            this.logout.Text = "Logout";
            this.logout.Click += new System.EventHandler(this.logout_Click);
            // 
            // Seller
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1200, 650);
            this.Controls.Add(this.logout);
            this.Controls.Add(this.Category_btn);
            this.Controls.Add(this.Product_btn);
            this.Controls.Add(this.close);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Seller";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Seller";
            this.Load += new System.EventHandler(this.Seller_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Seller_grid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.Framework.UI.BunifuThinButton2 Category_btn;
        private Bunifu.Framework.UI.BunifuThinButton2 Product_btn;
        private System.Windows.Forms.Label close;
        private System.Windows.Forms.Panel panel1;
        private Guna.UI2.WinForms.Guna2DataGridView Seller_grid;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Refresh_btn;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Delete_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Edit_btn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Add_btn;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox sellerPhone_txt;
        private Bunifu.UI.WinForms.BunifuTextBox sellerAge_txt;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox sellerName_txt;
        private Bunifu.UI.WinForms.BunifuTextBox sellerID_txt;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox sellerPassoword_set_txt;
        private System.Windows.Forms.Label logout;
    }
}